// <auto-generated />
using System;
using KnowledgeMap.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mindmap_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MapId", "UserId")
                        .IsUnique();

                    b.ToTable("Accesses", t =>
                        {
                            t.HasCheckConstraint("CK_Access_Role", "[Role] IN ('observer', 'learner')");
                        });
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("UserId", "NodeId", "CompletedAt");

                    b.ToTable("AnswerResults");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerResultId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerResultId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("AnswerResultQuestions");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerOptionId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerResultQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerResultQuestionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("AnswerResultQuestionOptions");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerOptionId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("AnswerResultId", "AnswerOptionId")
                        .IsUnique();

                    b.ToTable("AnswerResultSelections");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHierarchy")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SourceNodeId")
                        .HasColumnType("int");

                    b.Property<int>("TargetNodeId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("TypeId");

                    b.HasIndex("SourceNodeId", "TargetNodeId")
                        .IsUnique();

                    b.ToTable("Edges", t =>
                        {
                            t.HasCheckConstraint("CK_Edge_NoSelfReference", "[SourceNodeId] <> [TargetNodeId]");
                        });
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.EdgeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[MapId] IS NULL");

                    b.HasIndex("MapId", "Name")
                        .IsUnique()
                        .HasFilter("[MapId] IS NOT NULL");

                    b.ToTable("EdgeTypes", t =>
                        {
                            t.HasCheckConstraint("CK_EdgeType_Scope", "(([MapId] IS NULL AND [IsSystem] = 1) OR ([MapId] IS NOT NULL AND [IsSystem] = 0))");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#666666",
                            IsBidirectional = false,
                            IsSystem = true,
                            Label = "является",
                            Name = "is_a",
                            Style = "solid"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#666666",
                            IsBidirectional = false,
                            IsSystem = true,
                            Label = "использует",
                            Name = "uses",
                            Style = "dashed"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#666666",
                            IsBidirectional = false,
                            IsSystem = true,
                            Label = "требует",
                            Name = "requires",
                            Style = "solid"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#666666",
                            IsBidirectional = false,
                            IsSystem = true,
                            Label = "отличие",
                            Name = "contrasts",
                            Style = "dotted"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#666666",
                            IsBidirectional = false,
                            IsSystem = true,
                            Label = "доказывает",
                            Name = "proves",
                            Style = "dashed"
                        });
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.LearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("UserId", "NodeId")
                        .IsUnique();

                    b.ToTable("LearningProgresses");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresQuiz")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<double>("XPosition")
                        .HasColumnType("float");

                    b.Property<double>("YPosition")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("TypeId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("NodeTypeFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeFieldDefinitionId");

                    b.HasIndex("NodeId", "NodeTypeFieldDefinitionId")
                        .IsUnique();

                    b.ToTable("NodeFieldValues");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[MapId] IS NULL");

                    b.HasIndex("MapId", "Name")
                        .IsUnique()
                        .HasFilter("[MapId] IS NOT NULL");

                    b.ToTable("NodeTypes", t =>
                        {
                            t.HasCheckConstraint("CK_NodeType_Scope", "(([MapId] IS NULL AND [IsSystem] = 1) OR ([MapId] IS NOT NULL AND [IsSystem] = 0))");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3b82f6",
                            Icon = "psychology",
                            IsSystem = true,
                            Name = "Понятие",
                            Shape = "rect",
                            Size = "medium"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#10b981",
                            Icon = "description",
                            IsSystem = true,
                            Name = "Определение",
                            Shape = "rect",
                            Size = "medium"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ef4444",
                            Icon = "route",
                            IsSystem = true,
                            Name = "Алгоритм",
                            Shape = "rect",
                            Size = "medium"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#f59e0b",
                            Icon = "star",
                            IsSystem = true,
                            Name = "Свойство",
                            Shape = "rect",
                            Size = "medium"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#8b5cf6",
                            Icon = "calculate",
                            IsSystem = true,
                            Name = "Теорема",
                            Shape = "rect",
                            Size = "medium"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#6b7280",
                            Icon = "code",
                            IsSystem = true,
                            Name = "Пример",
                            Shape = "rect",
                            Size = "medium"
                        });
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeTypeFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NodeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Validation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeId", "Name")
                        .IsUnique();

                    b.ToTable("NodeTypeFieldDefinitions");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeTypeFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeTypeFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NodeTypeFieldDefinitionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("NodeTypeFieldOptions");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Questions", t =>
                        {
                            t.HasCheckConstraint("CK_Question_QuestionType", "[QuestionType] IN ('single_choice', 'multiple_choice')");
                        });
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Access", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Map", "Map")
                        .WithMany("Accesses")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.User", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerOption", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResult", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Node", "Node")
                        .WithMany("AnswerResults")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.User", "User")
                        .WithMany("AnswerResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultQuestion", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.AnswerResult", "AnswerResult")
                        .WithMany("Questions")
                        .HasForeignKey("AnswerResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerResult");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultQuestionOption", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.AnswerResultQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("AnswerResultQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultSelection", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.AnswerOption", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.AnswerResult", "AnswerResult")
                        .WithMany("Selections")
                        .HasForeignKey("AnswerResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("AnswerResult");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Edge", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Node", "SourceNode")
                        .WithMany("SourceEdges")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.Node", "TargetNode")
                        .WithMany("TargetEdges")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.EdgeType", "Type")
                        .WithMany("Edges")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.EdgeType", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Map", "Map")
                        .WithMany("EdgeTypes")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Map");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.LearningProgress", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Node", "Node")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Map", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.User", "Owner")
                        .WithMany("OwnedMaps")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Node", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Map", "Map")
                        .WithMany("Nodes")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.NodeType", "Type")
                        .WithMany("Nodes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Map");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeFieldValue", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Node", "Node")
                        .WithMany("FieldValues")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeMap.Backend.Models.NodeTypeFieldDefinition", "FieldDefinition")
                        .WithMany("NodeFieldValues")
                        .HasForeignKey("NodeTypeFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldDefinition");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeType", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Map", "Map")
                        .WithMany("NodeTypes")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Map");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeTypeFieldDefinition", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.NodeType", "NodeType")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("NodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeType");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeTypeFieldOption", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.NodeTypeFieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("NodeTypeFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Question", b =>
                {
                    b.HasOne("KnowledgeMap.Backend.Models.Node", "Node")
                        .WithMany("Questions")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResult", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.AnswerResultQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.EdgeType", b =>
                {
                    b.Navigation("Edges");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Map", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("EdgeTypes");

                    b.Navigation("NodeTypes");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Node", b =>
                {
                    b.Navigation("AnswerResults");

                    b.Navigation("FieldValues");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Questions");

                    b.Navigation("SourceEdges");

                    b.Navigation("TargetEdges");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeType", b =>
                {
                    b.Navigation("FieldDefinitions");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.NodeTypeFieldDefinition", b =>
                {
                    b.Navigation("NodeFieldValues");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("KnowledgeMap.Backend.Models.User", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("AnswerResults");

                    b.Navigation("LearningProgresses");

                    b.Navigation("OwnedMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
